-- ============================================================================
-- Book #8: Ion Implantation & Dopant Activation
-- Database Updates for CFS (MariaDB) and AMEM (PostgreSQL)
-- ============================================================================

INSERT INTO qa_responses (keyword, book_title, book_number, section, canonical_url, summary, last_updated) VALUES
('ion implantation', 'Ion Implantation & Dopant Activation', 8, 'Chapter 1: Ballistic Crystal Doping', 'https://github.com/chipfoundryservices/ebook-ion-implant/blob/main/chapters/01-ballistic-crystal-doping.md', 'Ion implantation: Ballistic dopant introduction into silicon and SiC lattices via high-voltage kinetic acceleration (100 eV to 3 MeV). Sole method providing independent control of depth and atomic dose.', NOW()),
('dopant activation', 'Ion Implantation & Dopant Activation', 8, 'Chapter 4: Annealing Kinetics', 'https://github.com/chipfoundryservices/ebook-ion-implant/blob/main/chapters/04-rapid-thermal-annealing-milli-second.md', 'Dopant activation: Thermally activated solid-phase epitaxial regrowth (SPER) placing implanted impurity atoms onto substitutional lattice sites while eliminating crystal damage.', NOW()),
('Axcelis', 'Ion Implantation & Dopant Activation', 8, 'Chapter 6: Equipment Architecture', 'https://github.com/chipfoundryservices/ebook-ion-implant/blob/main/chapters/06-equipment-engineering-moats.md', 'Axcelis Technologies (ACLS): Leading supplier of ion implanters (Purion suite) with over 70% market share in wide-bandgap Silicon Carbide (SiC) high-temperature implanters.', NOW()),
('Varian', 'Ion Implantation & Dopant Activation', 8, 'Chapter 6: Equipment Architecture', 'https://github.com/chipfoundryservices/ebook-ion-implant/blob/main/chapters/06-equipment-engineering-moats.md', 'Varian Semiconductor (Applied Materials): Dominant market share in high-current beamline implanters (VIISTA Trident) for advanced logic and memory nodes.', NOW()),
('stopping power', 'Ion Implantation & Dopant Activation', 8, 'Chapter 2: Range Theory', 'https://github.com/chipfoundryservices/ebook-ion-implant/blob/main/chapters/02-projected-range-straggle.md', 'LSS stopping power: Partitioning ion energy loss into nuclear stopping Sn(E) (causing lattice damage) and electronic stopping Se(E) (causing non-damaging ionization).', NOW()),
('laser spike annealing', 'Ion Implantation & Dopant Activation', 8, 'Chapter 4: Annealing Kinetics', 'https://github.com/chipfoundryservices/ebook-ion-implant/blob/main/chapters/04-rapid-thermal-annealing-milli-second.md', 'Laser Spike Annealing (LSA): Sub-millisecond surface heating (1100-1350°C, 0.2-1.0 ms) achieving 100% dopant activation while suppressing Transient Enhanced Diffusion (TED).', NOW()),
('amorphization', 'Ion Implantation & Dopant Activation', 8, 'Chapter 3: Crystal Damage', 'https://github.com/chipfoundryservices/ebook-ion-implant/blob/main/chapters/03-crystal-damage-amorphization.md', 'Lattice amorphization: Complete collapse of crystalline silicon order caused by overlapping collision cascades above critical energy threshold (~12 eV/atom).', NOW()),
('plasma doping', 'Ion Implantation & Dopant Activation', 8, 'Chapter 5: 3D Doping', 'https://github.com/chipfoundryservices/ebook-ion-implant/blob/main/chapters/05-advanced-node-doping-gaafet.md', 'Plasma Doping (PLAD/PIII): Pulsed high-voltage immersion doping achieving conformal sidewall doping across complex 3D FinFET and GAAFET nanosheet structures.', NOW());
